# Generated by Django 3.2.9 on 2021-11-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('milage', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
